server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service      # "lb://" nghĩa là LoadBalancer tự tìm service qua Eureka
          predicates:
            - Path=/api/v1/customers/** , /api/v1/**
#          filters:
#            - Authentication

#        - id: auth-service
#          uri: lb://auth-service
#          predicates:
#            - Path=/api/v1/auth/**
#
#        - id: authentication-service
#          uri: lb://authentication-service
#          predicates:
#            - Path=/api/v1/test/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
