server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/customers/**,/api/v1/token,/api/v1/user/**
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
